# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_camera = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_camera.setGeometry(QtCore.QRect(8, 15, 771, 251))
        self.label_camera.setStyleSheet("border: 2px solid black;\n""background-color: white;\n""")
        self.label_camera.setText("")
        self.label_camera.setObjectName("label_camera")
        self.btn_start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(590, 430, 141, 131))
        self.btn_start.setObjectName("btn_start")
        self.textEdit_result = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_result.setGeometry(QtCore.QRect(20, 300, 561, 261))
        self.textEdit_result.setObjectName("textEdit_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_start.setText(_translate("MainWindow", "Start Camera"))
        self.textEdit_result.setPlaceholderText(_translate("MainWindow", "Recognized text will appear here...\"."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
